CREATE DATABASE ShopGiay
GO
USE [ShopGiay]
GO
/****** Object:  Table [dbo].[CT_DONHANG]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CT_DONHANG](
	[MaDonHang] [int] NOT NULL,
	[MaGiay] [int] NOT NULL,
	[GiaLucBan] [decimal](18, 0) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[ThanhTien] [decimal](18, 0) NULL,
 CONSTRAINT [PK_CT_DONHANG] PRIMARY KEY CLUSTERED 
(
	[MaDonHang] ASC,
	[MaGiay] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONHANG]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONHANG](
	[MaDonHang] [int] IDENTITY(1,1) NOT NULL,
	[TinhTrangGiaoHang] [bit] NULL,
	[NgayDat] [datetime] NULL,
	[NgayGiao] [datetime] NULL,
	[TongTien] [decimal](18, 0) NULL,
	[MaKH] [int] NULL,
 CONSTRAINT [PK_DONHANG] PRIMARY KEY CLUSTERED 
(
	[MaDonHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [int] IDENTITY(1,1) NOT NULL,
	[TaiKhoanKH] [varchar](50) NULL,
	[MatKhau] [varchar](50) NOT NULL,
	[HoTen] [nvarchar](50) NOT NULL,
	[EmailKH] [nchar](10) NULL,
	[DiaChiKH] [nvarchar](100) NULL,
	[DienThoaiKH] [varchar](10) NULL,
	[NgaySinh] [datetime] NULL,
	[TrangThai] [bit] NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIGIAY]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIGIAY](
	[MaLoai] [int] IDENTITY(1,1) NOT NULL,
	[TenLoai] [nvarchar](50) NOT NULL,
	[TrangThai] [bit] NULL,
	[GioiTinh] [bit] NULL,
 CONSTRAINT [PK_LOAIGIAY] PRIMARY KEY CLUSTERED 
(
	[MaLoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHACUNGCAP]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHACUNGCAP](
	[MaNCC] [int] IDENTITY(1,1) NOT NULL,
	[TenNCC] [nvarchar](50) NOT NULL,
	[DiaChi] [nvarchar](100) NULL,
	[DienThoai] [varchar](50) NULL,
	[TrangThai] [bit] NULL,
 CONSTRAINT [PK_NHACUNGCAP] PRIMARY KEY CLUSTERED 
(
	[MaNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUANLY]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUANLY](
	[TaiKhoanQL] [varchar](50) NOT NULL,
	[MatKhau] [varchar](50) NOT NULL,
	[HoTen] [nvarchar](50) NULL,
	[EmailQL] [varchar](50) NULL,
	[DienThoaiQL] [varchar](10) NULL,
	[TrangThai] [bit] NULL,
 CONSTRAINT [PK_QUANLY] PRIMARY KEY CLUSTERED 
(
	[TaiKhoanQL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MaGiay] [int] IDENTITY(1,1) NOT NULL,
	[TenGiay] [nvarchar](50) NOT NULL,
	[Size] [tinyint] NOT NULL,
	[AnhBia] [varchar](50) NULL,
	[GiaBan] [decimal](18, 0) NOT NULL,
	[MaThuongHieu] [int] NULL,
	[TrangThai] [bit] NULL,
	[MaNCC] [int] NULL,
	[MaLoai] [int] NULL,
	[ThoiGianBaoHanh] [int] NULL,
	[NgayCapNhat] [datetime] NULL,
	[SoLuongTon] [int] NOT NULL,
 CONSTRAINT [PK_SANPHAM] PRIMARY KEY CLUSTERED 
(
	[MaGiay] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THUONGHIEU]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THUONGHIEU](
	[MaThuongHieu] [int] IDENTITY(1,1) NOT NULL,
	[TenThuongHieu] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_THUONGHIEU] PRIMARY KEY CLUSTERED 
(
	[MaThuongHieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YKIENKHACHHANG]    Script Date: 6/7/2022 5:43:04 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YKIENKHACHHANG](
	[MAYKIEN] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](50) NULL,
	[HoTen] [varchar](50) NOT NULL,
	[NgayGui] [date] NULL,
	[NoiDung] [nvarchar](max) NOT NULL,
	[TrangThai] [bit] NULL,
 CONSTRAINT [PK_BAIDANHGIA] PRIMARY KEY CLUSTERED 
(
	[MAYKIEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[LOAIGIAY] ON 
GO
INSERT [dbo].[LOAIGIAY] ([MaLoai], [TenLoai], [TrangThai], [GioiTinh]) VALUES (1, N'Sandal Nam', 0, 1)
GO
INSERT [dbo].[LOAIGIAY] ([MaLoai], [TenLoai], [TrangThai], [GioiTinh]) VALUES (2, N'Sandal Nu', 0, 0)
GO
INSERT [dbo].[LOAIGIAY] ([MaLoai], [TenLoai], [TrangThai], [GioiTinh]) VALUES (3, N'Tong lao', 0, 1)
GO
INSERT [dbo].[LOAIGIAY] ([MaLoai], [TenLoai], [TrangThai], [GioiTinh]) VALUES (4, N'to ong', 0, 0)
GO
SET IDENTITY_INSERT [dbo].[LOAIGIAY] OFF
GO
SET IDENTITY_INSERT [dbo].[NHACUNGCAP] ON 
GO
INSERT [dbo].[NHACUNGCAP] ([MaNCC], [TenNCC], [DiaChi], [DienThoai], [TrangThai]) VALUES (1, N'Thảo Nguyên', N'Bình Dương', N'0123456789', 0)
GO
SET IDENTITY_INSERT [dbo].[NHACUNGCAP] OFF
GO
SET IDENTITY_INSERT [dbo].[SANPHAM] ON 
GO
INSERT [dbo].[SANPHAM] ([MaGiay], [TenGiay], [Size], [AnhBia], [GiaBan], [MaThuongHieu], [TrangThai], [MaNCC], [MaLoai], [ThoiGianBaoHanh], [NgayCapNhat], [SoLuongTon]) VALUES (1, N'Nike 1', 30, N'van1.jpg', CAST(30000 AS Decimal(18, 0)), 1, 1, 1, 1, 3, CAST(N'2020-07-06T00:00:00.000' AS DateTime), 12)
GO
INSERT [dbo].[SANPHAM] ([MaGiay], [TenGiay], [Size], [AnhBia], [GiaBan], [MaThuongHieu], [TrangThai], [MaNCC], [MaLoai], [ThoiGianBaoHanh], [NgayCapNhat], [SoLuongTon]) VALUES (2, N'Vans 1', 39, N'nike1.jpg', CAST(350000 AS Decimal(18, 0)), 2, 1, 1, 1, 4, CAST(N'2022-09-05T00:00:00.000' AS DateTime), 12)
GO
SET IDENTITY_INSERT [dbo].[SANPHAM] OFF
GO
SET IDENTITY_INSERT [dbo].[THUONGHIEU] ON 
GO
INSERT [dbo].[THUONGHIEU] ([MaThuongHieu], [TenThuongHieu]) VALUES (1, N'Nike')
GO
INSERT [dbo].[THUONGHIEU] ([MaThuongHieu], [TenThuongHieu]) VALUES (2, N'Vans')
GO
SET IDENTITY_INSERT [dbo].[THUONGHIEU] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__KHACHHAN__7ED9643FF0F6FC75]    Script Date: 6/7/2022 5:43:04 AM ******/
ALTER TABLE [dbo].[KHACHHANG] ADD UNIQUE NONCLUSTERED 
(
	[EmailKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__KHACHHAN__9A123AA24F4CEAA8]    Script Date: 6/7/2022 5:43:04 AM ******/
ALTER TABLE [dbo].[KHACHHANG] ADD UNIQUE NONCLUSTERED 
(
	[TaiKhoanKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__QUANLY__7ED955FCB133CB14]    Script Date: 6/7/2022 5:43:04 AM ******/
ALTER TABLE [dbo].[QUANLY] ADD UNIQUE NONCLUSTERED 
(
	[EmailQL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__QUANLY__9A120A6629656DDD]    Script Date: 6/7/2022 5:43:04 AM ******/
ALTER TABLE [dbo].[QUANLY] ADD UNIQUE NONCLUSTERED 
(
	[TaiKhoanQL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KHACHHANG] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[LOAIGIAY] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[NHACUNGCAP] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[QUANLY] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[SANPHAM] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[YKIENKHACHHANG] ADD  DEFAULT ((0)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[CT_DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONHANG] FOREIGN KEY([MaDonHang])
REFERENCES [dbo].[DONHANG] ([MaDonHang])
GO
ALTER TABLE [dbo].[CT_DONHANG] CHECK CONSTRAINT [FK_DONHANG]
GO
ALTER TABLE [dbo].[CT_DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_SANPHAM_2] FOREIGN KEY([MaGiay])
REFERENCES [dbo].[SANPHAM] ([MaGiay])
GO
ALTER TABLE [dbo].[CT_DONHANG] CHECK CONSTRAINT [FK_SANPHAM_2]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_2] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [FK_KHACHHANG_2]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_LOAIGIAY] FOREIGN KEY([MaLoai])
REFERENCES [dbo].[LOAIGIAY] ([MaLoai])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_LOAIGIAY]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_NHACUNGCAP] FOREIGN KEY([MaNCC])
REFERENCES [dbo].[NHACUNGCAP] ([MaNCC])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_NHACUNGCAP]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FL_THUONGHIEU] FOREIGN KEY([MaThuongHieu])
REFERENCES [dbo].[THUONGHIEU] ([MaThuongHieu])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FL_THUONGHIEU]
GO
ALTER TABLE [dbo].[CT_DONHANG]  WITH CHECK ADD CHECK  (([SoLuong]>=(0)))
GO
ALTER TABLE [dbo].[CT_DONHANG]  WITH CHECK ADD CHECK  (([ThanhTien]>=(0)))
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD CHECK  (([GiaBan]>(0)))
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD CHECK  (([SoLuongTon]>=(0)))
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD CHECK  (([ThoiGianBaoHanh]>=(0)))
GO
