<?xml version="1.0" encoding="utf-8"?><Database Name="WebShopGiayDep" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CAONGUYEN\SQLEXPRESS;Initial Catalog=WebShopGiayDep;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebShopGiayDepConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAIDANHGIA" Member="BAIDANHGIAs">
    <Type Name="BAIDANHGIA">
      <Column Name="MaBaiDanhGia" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="MaGiay" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="NgayGui" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SANPHAM_BAIDANHGIA" Member="SANPHAM" ThisKey="MaGiay" OtherKey="MaGiay" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="KHACHHANG_BAIDANHGIA" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaGiay" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGiay" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AnhBia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ThuongHieu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ThoiGianBaoHanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_BAIDANHGIA" Member="BAIDANHGIAs" ThisKey="MaGiay" OtherKey="MaGiay" Type="BAIDANHGIA" />
      <Association Name="SANPHAM_CT_DONHANG" Member="CT_DONHANGs" ThisKey="MaGiay" OtherKey="MaGiay" Type="CT_DONHANG" />
      <Association Name="LOAIGIAY_SANPHAM" Member="LOAIGIAY" ThisKey="MaLoai" OtherKey="MaLoai" Type="LOAIGIAY" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="MaNCC" OtherKey="MaNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_DONHANG" Member="CT_DONHANGs">
    <Type Name="CT_DONHANG">
      <Column Name="MaDonHang" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGiay" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaLucBan" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_CT_DONHANG" Member="SANPHAM" ThisKey="MaGiay" OtherKey="MaGiay" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="DONHANG_CT_DONHANG" Member="DONHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MaDonHang" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Association Name="DONHANG_CT_DONHANG" Member="CT_DONHANGs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CT_DONHANG" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaiKhoanKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailKH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DiaChiKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoaiKH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KHACHHANG_BAIDANHGIA" Member="BAIDANHGIAs" ThisKey="MaKH" OtherKey="MaKH" Type="BAIDANHGIA" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MaKH" OtherKey="MaKH" Type="DONHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIGIAY" Member="LOAIGIAYs">
    <Type Name="LOAIGIAY">
      <Column Name="MaLoai" Type="System.Char" DbType="Char(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAIGIAY_SANPHAM" Member="SANPHAMs" ThisKey="MaLoai" OtherKey="MaLoai" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNCC" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="MaNCC" OtherKey="MaNCC" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.QUANLY" Member="QUANLies">
    <Type Name="QUANLY">
      <Column Name="TaiKhoanQL" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailQL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DienThoaiQL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>